<a href="https://colab.research.google.com/github/ljm9748/deepstudy/blob/master/nlp_prev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [2]:
sr = pd.Series([17000, 18000, 1000, 5000],
       index=["피자", "치킨", "콜라", "맥주"])
print(sr)

피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64


In [3]:
print(sr.values)

[17000 18000  1000  5000]


In [4]:
print(sr.index)

Index(['피자', '치킨', '콜라', '맥주'], dtype='object')


In [5]:
values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index=index, columns=columns)
print(df)

       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [6]:
print(df.index)

Index(['one', 'two', 'three'], dtype='object')


In [7]:
print(df.columns)

Index(['A', 'B', 'C'], dtype='object')


In [8]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]
df = pd.DataFrame(data)
print(df)

      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [10]:
df = pd.DataFrame(data, columns=['학번', '이름', '점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [11]:
data = { '학번' : ['1000', '1001', '1002', '1003', '1004', '1005'],
'이름' : [ 'Steve', 'James', 'Doyeon', 'Jane', 'Pilwoong', 'Tony'],
         '점수': [90.72, 78.09, 98.43, 64.19, 81.30, 99.14]}

df = pd.DataFrame(data)
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [12]:
print(df.head(3))

     학번      이름     점수
0  1000   Steve  90.72
1  1001   James  78.09
2  1002  Doyeon  98.43


In [15]:
print(df.tail())

     학번        이름     점수
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [14]:
print(df['학번'])

0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: 학번, dtype: object


In [0]:
import numpy as np

In [18]:
a = np.array([1, 2, 3, 4, 5]) 
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [19]:
b = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(b) 

[[10 20 30]
 [60 70 80]]


In [20]:
print(b.ndim) 

2


In [21]:
print(b.shape)

(2, 3)


In [22]:
a = np.zeros((2,3)) 
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
a = np.ones((2,3)) 
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
a = np.full((2,2), 7) 
print(a)

[[7 7]
 [7 7]]


In [25]:
a = np.eye(3) 
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
a = np.random.random((2,2))
print(a)

[[0.15992499 0.36782249]
 [0.15943903 0.90123829]]


In [27]:
a = np.arange(10) 
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
a = np.arange(1, 10, 2) 
print(a)

[1 3 5 7 9]


In [29]:
print(np)

<module 'numpy' from '/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'>


In [41]:
a = np.array(np.arange(30))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [0]:
a=np.reshape(a,(5,6))

In [43]:
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [45]:
print(a)

[[1 2 3]
 [4 5 6]]


In [46]:
b=a[0:2, 0:2]
print(b)


[[1 2]
 [4 5]]


In [48]:
b=a[0, :]
print(b)

[1 2 3]


In [49]:
b=a[:, 1] 
print(b)

[2 5]


In [50]:
a = np.array([[1,2], [4,5], [7,8]])
b = a[[2, 1],[1, 0]] 
print(b)

[8 4]


In [51]:
a

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
x = np.array([1,2,3])
y = np.array([4,5,6])

b = x + y 
print(b)

[5 7 9]


In [53]:
b = x - y 
print(b)

[-3 -3 -3]


In [54]:
b = b * x 
print(b)

[-3 -6 -9]


In [55]:
b = b / x 
print(b)

[-3. -3. -3.]


In [56]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]


In [0]:
import matplotlib.pyplot as plt

In [58]:
plt.title('test')
plt.plot([1,2,3,4],[2,4,8,6])
plt.show()

In [59]:
plt.title('test')
plt.plot([1,2,3,4],[2,4,8,6])
plt.xlabel('hours')
plt.ylabel('score')
plt.show()