<a href="https://colab.research.google.com/github/ljm9748/deepstudy/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [1]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [2]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))


Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


30. Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name). Go to the editor
first_names = (Betsey, Shelley, Lanell, Genesis, Margery)
last_names = (Battle, Brien, Plotner, Stahl, Woolum)
Expected Output:
[1 3 2 4 0]

In [3]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]
ERROR! Session/line number was not unique in database. History logging moved to new session 59


40. Write a NumPy program to create a new array of 3*5, filled with 2. Go to the editor
Expected Output:
[[2 2 2 2 2]
[2 2 2 2 2]
[2 2 2 2 2]]
[[2 2 2 2 2]
[2 2 2 2 2]
[2 2 2 2 2]]

In [4]:
x = np.full((3, 5), 2, dtype=np.uint)
print(x)
#using no.ones
y = np.ones([3, 5], dtype=np.uint) *2
print(y)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


50. Write a NumPy program to find the 4th element of a specified array. Go to the editor
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Forth e1ement of the array:
6

In [5]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
e1 = x.flat[3]
print("Forth e1ement of the array:")
print(e1)

[[ 2  4  6]
 [ 6  8 10]]
Forth e1ement of the array:
6


60. Write a NumPy program to convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array. Go to the editor
Sample array: (10,20,30), (40,50,60)
Expected Output:
[[[10 40]]
[[20 50]]
[[30 60]]]

In [6]:
a = np.array([[10],[20],[30]])
b = np.array([[40],[50],[60]])
c = np.dstack((a, b))
print(c)

[[[10 40]]

 [[20 50]]

 [[30 60]]]


 Write a NumPy program to create display every element of a NumPy array. Go to the editor
Expected Output:
0 1 2 3 4 5 6 7 8 9 10 11

In [7]:
x = np.arange(12).reshape(3, 4)
for x in np.nditer(x):
    print(x,end=' ')
print()

0 1 2 3 4 5 6 7 8 9 10 11 


90. Write a NumPy program to remove the negative values in a NumPy array with 0. Go to the editor

Expected Output:
Original array:
[-1 -4 0 2 3 4 5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]

In [8]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x[x < 0] = 0
print(x)

Original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]
ERROR! Session/line number was not unique in database. History logging moved to new session 60


100. Write a NumPy program to take values from a source array and put them at specified indices of another array. Go to the editor
Expected Output:
[ 10. 10. 20. 30. 30.]
Put 0 and 40 in first and fifth position of the above array
Array x after put two values: [ 0. 10. 20. 30. 40.]

In [9]:
import numpy as np
x = np.array([10, 10, 20, 30, 30], float)
print(x)
print("Put 0 and 40 in first and fifth position of the above array")
y = np.array([0, 40, 60], float) 
x.put([0, 4], y)
print("Array x, after putting two values:")
print(x)

[10. 10. 20. 30. 30.]
Put 0 and 40 in first and fifth position of the above array
Array x, after putting two values:
[ 0. 10. 20. 30. 40.]
